import_path: github.com/kbhonagiri16/visualization

language: go
go:
  - 1.7.5
  - 1.8
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - make all

sudo: false
